# Generated by Django 4.2.3 on 2023-08-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapterNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='moduleNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title', 'tutor')},
        ),
    ]
